name: sleeping_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  font_awesome_flutter: ^10.7.0
  # path_provider: ^2.1.4
  # rate_my_app: ^2.2.0
  flutter_sound: ^9.8.1
  provider: ^6.1.2
  # mic_stream: ^0.7.1+2
  audioplayers: ^6.0.0
  # eva_icons_flutter: ^3.1.0
  # syncfusion_flutter_charts: ^26.2.11
  table_calendar: ^3.1.2
  intl: ^0.19.0
  share: ^2.0.4
  google_fonts: ^6.2.1
  # chewie: ^1.8.3
  carousel_slider: ^5.0.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  # flutter_zoom_drawer: ^3.2.0
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.1
  # cloud_firestore: ^5.4.4
  shimmer: ^3.0.0
  # google_sign_in: ^6.2.1
  # device_info_plus: ^11.1.1
  flutter_local_notifications: ^12.0.0
  flutter_timezone: ^1.0.8
  timezone:
  permission_handler: ^11.0.1
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/
    - assets/image/
    - assets/models/
    - assets/icons/
    - assets/screen_shots/
    - assets/

  # fonts:
  #  - family: NewAmsterdam
  #   fonts:
  #    - asset: assets/fonts/NewAmsterdam-Regular.ttf
  #     weight: 400
  #  - asset: assets/fonts/NewAmsterdam-Regular.ttf
  #   weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
